### ISSUE TITLE
npm-force-resolutions not working

### ISSUE THREAD

**Issue by petercarpenter-santander** [hector-js/stub-backend#78]
**Describe the bug**
When I install newer versions of the package, I get the following error:

```
> @hectorjs/stub-backend@1.26.1 preinstall /Users/e1200533/development/repos/sme-frontend-servicing/mocks-deployment/node_modules/@hectorjs/stub-backend
> npx npm-force-resolutions

npx: installed 6 in 2.488s
Error: ENOENT: no such file or directory, open './package-lock.json'
``` 

It looks to me like its looking for the package-lock.json inside `/node_modules/@hectorjs/stub-backend`, but its not there. Why was this preinstall script needed? I think this will break fresh installs for everyone...

**To Reproduce**
1. Have a project with @hectorjs/stub-backend defined in the package json
2. install the dependencies from scratch

**Expected behavior**
The dependencies should install,  not error

**Comment by hector-js** [comment]
Hi @petercarpenter-santander, 

Sorry for the delay answering. Basically, it was temporary included to fix quickly [one vulnerability](https://github.com/hector-js/stub-backend/security/dependabot/package-lock.json/ansi-regex/open) and it broke the installation :pensive:. I remove force resolutions and It is already fixed in the newer version : [1.27.0](https://www.npmjs.com/package/@hectorjs/stub-backend).
Please, give it a try 😄.
